### ISSUE TITLE
Remove profile functionality?

### ISSUE THREAD

**Issue by msmichellegar** [jmnr/dark#46]
I don't profiles are super-important to Dark's functionality, so should we just let it go and focus on bringing back the love button? Discuss.

**Comment by wallcrawler** [comment]
hahaha after sweating blood to get the auth working i am very committed to keeping profiles.

the love button is coming back. the way i see it is that the transparency of the pics is determined by the last time it was clicked (eg currentTimestamp  - lastClickedTimestamp / 24hrs = percentage)

**Comment by msmichellegar** [comment]
Haha. Ok. Profiles shall be kept! We just need to figure out filtering the photos to only the user's own for that page then.

Looking forward to the love button comeback.
