### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by msmichellegar** [jmnr/dark#47]
Should we put all backend files into an "app", "backend" or "api" folder? Like, routes, handlers etc. It's just a bit messy right now.

**Comment by wallcrawler** [comment]
i've already moved everything locally, have a push to make tomorrow once ive ironed things out. including a working love button...

**Comment by msmichellegar** [comment]
Cool! Omg!

**Comment by wallcrawler** [comment]
well there it is, but if you have any other ideas, like 'api' or 'lib' etc, go ahead
